version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: mongo-movies-app
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/moviesdb
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    command: npm run dev

volumes:
  mongo_data:
